site_name: FastDeploy
repo_url: https://github.com/laranapoli/fast-deploy
repo_name: laranapoli/fast-deploy
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  # logo: assets/logo.png
  # favicon: assets/logo.png assets fica dentro de docs!

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

watch:
  - fast_deploy

plugins:
- macros
- mkdocstrings:
    handlers: 
      python:
        paths: [fast_deploy, fast_deploy/loaders, fast_deploy/api]

extra:
  commands:
    run: poetry run deploy
