name: ci-pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar arquivos do repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: papodaca/install-docker-action@main

      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias do projeto
        run: poetry install --without doc

      - name: Rodar testes
        run: poetry run task test
